channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pre-commit
  - pytest-cov
  - pytest-asyncio
  - code-server>=3.2
  - jupyter-vscode-proxy
  - pip
  - pip:
    - carbonplan_data
    - dask
    - geojson-pydantic==0.6.2
    - locust
    - locust_plugins
    - loguru==0.7.0
    - ndpyramid
    - papermill==2.4.0
    - psycopg==3.1.9
    - psycopg-binary==3.1.9
    - psycopg-pool
    - pypgstac==0.7.9
    - rio_stac<0.7,>=0.6
    - rio-tiler==4.1.11
    - statsmodels
    - titiler-pgstac
    - titiler
