channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pre-commit
  - pytest-cov
  - pytest-asyncio
  - code-server>=3.2
  - jupyter-vscode-proxy
  - emacs
  - pip
  - pip:
    - carbonplan_data
    - dask
    - geojson-pydantic
    - locust
    - locust_plugins
    - loguru
    - ndpyramid
    - papermill
    - psycopg
    - psycopg-binary
    - psycopg-pool
    - pypgstac
    - rio-tiler
    - statsmodels
    - titiler-pgstac
    - titiler
